spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: lfy31678
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
aliyun:
  oss:
    endpoint:  # 你的OSS服务地址
    accessKeyId:  # 你的Access Key ID
    accessKeySecret:  # 你的Access Key Secret
    bucketName:  # 你的Bucket名称
